
package com.byd.emg.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SAPERP_PM_CN_ORDER_DATA_SI", targetNamespace = "urn:ERP:DR_PM_ORDER_DATA")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SAPERPPMCNORDERDATASI {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.byd.emg.webservice.ZCNORDERINFORFCResponse
     */
    @WebMethod(operationName = "SAPERP_PM_CN_ORDER_DATA_SI", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ZCN_ORDER_INFO_RFC.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    public ZCNORDERINFORFCResponse saperpPMCNORDERDATASI(
        @WebParam(name = "ZCN_ORDER_INFO_RFC", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
        ZCNORDERINFORFC parameters);

}
