
package com.byd.emg.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SAPERP_PM_CN_ORDER_DATA_SIService", targetNamespace = "urn:ERP:DR_PM_ORDER_DATA", wsdlLocation = "file:/F:/SAP/SAPERP_PM_CN_ORDER_DATA_SIService.wsdl")
public class SAPERPPMCNORDERDATASIService
    extends Service
{

    private final static URL SAPERPPMCNORDERDATASISERVICE_WSDL_LOCATION;
    private final static WebServiceException SAPERPPMCNORDERDATASISERVICE_EXCEPTION;
    private final static QName SAPERPPMCNORDERDATASISERVICE_QNAME = new QName("urn:ERP:DR_PM_ORDER_DATA", "SAPERP_PM_CN_ORDER_DATA_SIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/F:/SAP/SAPERP_PM_CN_ORDER_DATA_SIService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAPERPPMCNORDERDATASISERVICE_WSDL_LOCATION = url;
        SAPERPPMCNORDERDATASISERVICE_EXCEPTION = e;
    }

    public SAPERPPMCNORDERDATASIService() {
        super(__getWsdlLocation(), SAPERPPMCNORDERDATASISERVICE_QNAME);
    }

    public SAPERPPMCNORDERDATASIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAPERPPMCNORDERDATASISERVICE_QNAME, features);
    }

    public SAPERPPMCNORDERDATASIService(URL wsdlLocation) {
        super(wsdlLocation, SAPERPPMCNORDERDATASISERVICE_QNAME);
    }

    public SAPERPPMCNORDERDATASIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAPERPPMCNORDERDATASISERVICE_QNAME, features);
    }

    public SAPERPPMCNORDERDATASIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SAPERPPMCNORDERDATASIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SAPERPPMCNORDERDATASI
     */
    @WebEndpoint(name = "HTTP_Port")
    public SAPERPPMCNORDERDATASI getHTTPPort() {
        return super.getPort(new QName("urn:ERP:DR_PM_ORDER_DATA", "HTTP_Port"), SAPERPPMCNORDERDATASI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SAPERPPMCNORDERDATASI
     */
    @WebEndpoint(name = "HTTP_Port")
    public SAPERPPMCNORDERDATASI getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:ERP:DR_PM_ORDER_DATA", "HTTP_Port"), SAPERPPMCNORDERDATASI.class, features);
    }

    /**
     * 
     * @return
     *     returns SAPERPPMCNORDERDATASI
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SAPERPPMCNORDERDATASI getHTTPSPort() {
        return super.getPort(new QName("urn:ERP:DR_PM_ORDER_DATA", "HTTPS_Port"), SAPERPPMCNORDERDATASI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SAPERPPMCNORDERDATASI
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SAPERPPMCNORDERDATASI getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:ERP:DR_PM_ORDER_DATA", "HTTPS_Port"), SAPERPPMCNORDERDATASI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAPERPPMCNORDERDATASISERVICE_EXCEPTION!= null) {
            throw SAPERPPMCNORDERDATASISERVICE_EXCEPTION;
        }
        return SAPERPPMCNORDERDATASISERVICE_WSDL_LOCATION;
    }

}
